### ISSUE TITLE
Feature request: support keydown/keyup event

### ISSUE THREAD

**Issue by QiangF** [k0kubun/xremap#72]
I am looking a way to show tint2 bar on windows keydown and hide it on windows key up. There are other uses and a similar request on xkeysnail repo https://github.com/mooz/xkeysnail/issues/93

Thank you!

**Comment by k0kubun** [comment]
To understand what you want to do more, could you write an example YAML config you want to write? Is there a command to talk to tint2 bar?

Please assume that the feature is going to be under `modmap`. I don't intend to support modifier keys like windows as the primary key that triggers events in `keymap`.

**Comment by QiangF** [comment]
What I am trying to is run a command on keydown event.
Tint2 will pop up when mouse is over bottom left, so the command is

    xdotool mousemove 0 3600

And run another command on keyup event

    xdotool mousemove 0 0

**Comment by k0kubun** [comment]
Could you test this branch? https://github.com/k0kubun/xremap/pull/75

Some caveats with this feature:

* We only support executing commands on `press` and `release`.
  * At least I don't intend to support generating transformed key events here. It could easily generate a weird sequence of events and it's hard to make everything right, supporting that feature.
  * Anyway it seems like the only use case of this feature.
* You must specify both `press` and `release`.
  * If you need only one command to be executed, you should just use the `launch` action in `keymap`.

**Comment by k0kubun** [comment]
I'll close this until this issue becomes actionable on my end. I'll close the PR too, but I'll leave the branch kept for a while so that you can test it.

**Comment by QiangF** [comment]
Sorry for the delay.ed reply. I still need some time to learn how to build this branch. I hope someone might be interested in this feature. Thank you!

**Comment by k0kubun** [comment]
Can you try [xremap.zip](https://github.com/k0kubun/xremap/files/8106153/xremap.zip) then? It's a linux-x86_64 binary for X11 built on the branch.

**Comment by QiangF** [comment]
It works wonderfully for executing different command on keydown and keyup. But I can't use the key as normal modifier when combined with other keys. Can you please get the held behavior back?

Now we get similar behavior like i3wm, when windows key is pressed, the auto hidden status bar is shown, of course we need the windows key as a modifier too.

**Comment by k0kubun** [comment]
> of course we need the windows key as a modifier too.

To me, https://github.com/mooz/xkeysnail/issues/93 didn't seem like it, but I got it now.

So you want such an event to be kept triggered. To help me design the feature, would you use the same feature for non-modifier keys and also want that to trigger events as well as the command, or would you use it only for modifier keys?

**Comment by QiangF** [comment]
I think it only needed for modifier keys: add an additional function to trigger external command, and trigger the original events as well.

**Comment by QiangF** [comment]
There are other use cases. Such as app switching, keydown pops up the app panel, and use the same modifier combination to move forward or backward depending on where you are. This saves time because your finger is already on the modifier and is already pressed down.

**Comment by k0kubun** [comment]
yon mean, modifer keydown to open the app switch panel, arrow keys or Emacs binding to select an app, and modifier keyup to open the selected app?

**Comment by QiangF** [comment]
No. That's too complicated. Just add the function you already added and let the application or window manager has windows key-down, key-held, key-up event too (since key-down is consumed, if key-held is the same as key-down, just repeat it) . The other functions should be realized elsewhere.

**Comment by k0kubun** [comment]
I just rephrased your other use cases that can be achieved by implementing what you've just said 😕, but I guess I understand what you're saying anyway.

As we will not transform key events by this, I think this feature can be under `keymap` instead of `modmap`. Please give me some time to think about how to naturally implement this though. For now, I can also prepare a binary that just implements what you asked.

**Comment by QiangF** [comment]
I replaced xkeysnail with xremap. I have all my other needs. I am in no hurry.
This is my current config file https://gist.github.com/QiangF/dc18e24f0a861dbbb9b086533a3c81f2

**Comment by k0kubun** [comment]
Here's a new linux-x86_64 binary for X11 that dispatches modifier key events as well as command invocation with your config: [xremap.zip](https://github.com/k0kubun/xremap/files/8121980/xremap.zip) (branch: https://github.com/k0kubun/xremap/pull/79)

I'll let you know when it gets official support, but please use this binary in the meantime.

**Comment by k0kubun** [comment]
Released https://github.com/k0kubun/xremap/pull/79 in v0.5.1. Note that the syntax was slightly modified; you need to use `{ launch: ... }` to run a command.

**Comment by QiangF** [comment]
The behavior has been changed. Now the key can't be used as a modifier. And it doesn't work for polybar.

    modmap:
      - name: Global
        remap:
          Win_L:
           press: { launch: ["polybar-msg", "cmd", "show"] } # Required
           release: { launch: ["polybar-msg", "cmd", "hide"] } # Required

What supposed to work is:

When the windows key is pressed the system bar shows up, and the bar disappear on windows key release. Just like i3-bar. While keep the windows key as a modifier.

**Comment by k0kubun** [comment]
Got it. Fixed in v0.7.3.

**Comment by QiangF** [comment]
The polybar-msg command still doesn't work. The two command "polybar-msg cmd show" and "polybar-msg cmd hide" work in terminal and in a tty. polybar use x window unmap and map to hide and show itself.

**Comment by QiangF** [comment]
I got it working with these commands

    xdo raise -N Polybar
    xdo lower -N Polybar

**Comment by QiangF** [comment]
The problem with raise or lower is that they don't work for the tray module. hide and show is better.
